### PR TITLE
move logic to 'default' recipe

### PR DESCRIPTION
**Pull request by mburns**
Move the logic from `base` recipe to `default`, keeping an `include_recipe` for backwards compatibility. "base" as a recipe is an anti-pattern.

We can keep the old recipe around for ~1 version, then we can delete (and update `run_lists` accordingly).

### CODE REVIEW

**Comment by drenalin23** [comment]
I partially disagree.  The logic to fill the filebeat.logstash.hosts should go into the default recipe.
However the pattern I used in metrics-filebeat, is to name the recipe after the role that the prospectors are designed for - so I disagree that having a recipe named base to match the role base is an anti-pattern.

**Comment by mburns** [comment]
Ok, I see the pattern you're going for. I'm not sure I'm sold on it, but it makes sense.

Q: Why not move that role-specific filebeat logic (a single `filebeat_prospector` call, generally) to the appropriate recipe, at least where possible? Maybe there are more corner cases than I realize.

* `metrics-filebeat::query` -> `blueflood::query`
* `metrics-filebeat::rollup` -> `blueflood::rollup`

I'm not clear on what the added flexibility gains us, if we are already putting the recipe logic in a team-specific wrapper cookbook.

We've talked about a similar issue on the Monitoring side with our `cloud_monitoring` that has a `default` recipe, a `base`-like recipe, and `role`-specific recipes. /CC @shawnashlee

**Comment by drenalin23** [comment]
On number 2 above.  For me what it gets us long term is improved testing in a tighter feedback loop (both via travisCI and local unit/kitchen testing).  If we sprinkle filebeat configs (or crons are similar for me) then what if the LWRP changes or upstream config options change - then you may have tests, code all around either nodes, envs, cookbooks, etc and not one core place to find filebeat related options.  
For the filebeat example - say that adds 1 minute of testing to a kitchen suite for testing collector nodes, or to update/test a filebeat config for collector nodes I have to run the entire test suite for a collector.  IMHO both of those waste time - when in a standalone wrapper the tests can be run frequently and by virtue of freeing up the time I'd bet we end up with better quality tests.
That's some of my 2 cents on it.

**Comment by shawnashlee** [comment]
imho, I like using the `default` recipe, mostly due to how chef works and where I think people would look first. Im not against role specific recipes, but im more in the minimalist group and wouldn't mind the "extra clutter" of having tiny (job named?) recipes (easier for testing) that are included in a recipe named after roles.

**Comment by mburns** [comment]
fair enough.

**Pull request closed without merging**
